apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config-v1
  labels:
    app: django-server
data:
  SECRET_KEY: "secretkey"
  DEBUG: "False"
  DATABASE_URL: "postgres://test-k8s:OwOtBep9Frut@postgres-service:5432/test-k8s"
  ALLOWED_HOSTS: "127.0.0.1,star-burger.test"
  POSTGRES_USER: test-k8s
  POSTGRES_PASSWORD: OwOtBep9Frut
  POSTGRES_DB: test-k8s
