apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  startingDeadlineSeconds: 20
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 40
      template:
        spec:
          containers:
            - name: django
              image: eshinanase/django_app:latest
              command: ['python', 'manage.py', 'clearsessions']
              env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: SECRET_KEY
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: DATABASE_URL
          restartPolicy: Never
