version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_k8s
      POSTGRES_USER: test_k8s
      POSTGRES_PASSWORD: OwOtBep9Frut

  web:
    build: backend_main_django
    image: django_app
    volumes:
      - ./backend_main_django:/code
    environment:
      SECRET_KEY: secretkey
      DEBUG: True
      DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@db:5432/test_k8s
      ALLOWED_HOSTS: 127.0.0.1
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - db

volumes:
  db_data:
